name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
      if: github.event == 'push'
    - name: Run tests
      run: cargo test --verbose
      if: github.event == 'push'
